Temporarily test visibility up to 100 times to catch flake

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1335,6 +1335,17 @@ steps-tests: &steps-tests
           cd src
           (cd electron && node script/yarn test --runners=main --trace-uncaught --enable-logging --files $(circleci tests glob spec-main/*-spec.ts | circleci tests split))
           (cd electron && node script/yarn test --runners=remote --trace-uncaught --enable-logging --files $(circleci tests glob spec/*-spec.js | circleci tests split))
+          cd electron
+          for i in {1..100}
+          do
+            echo "TESTING VISIBILITY #:$i"
+            node script/yarn test --runners=main --trace-uncaught --enable-logging --files spec-main/visibility-state-spec.ts
+            if [[ "$?" -ne 0 ]]; then
+              echo "FOUND FAILURE after $i tries"
+              break
+            fi
+          done
+          echo "Done testing with $i tries"
     - run:
         name: Check test results existence
         command: |
